default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: xander
  password: helloworld

development:
  <<: *default
  database: label_demo_development


test:
  <<: *default
  database: label_demo_test
