default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: xander

development:
  <<: *default
  database: younility_development


test:
  <<: *default
  database: younility_test
